[package]
name = "yanp-r"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"

[dev-dependencies]
assert_matches = "1.5"
